# Generated by Django 6.0.3 on 2026-05-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmcs', '0002_allowancededuction_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
