# Generated by Django 6.0.3 on 2026-03-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('setup', '0008_nigstate_lga_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer_name',
            new_name='sender_name',
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='receiver_alt_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='receiver_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sender_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_state_item', to='setup.nigstate'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waybillNo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='createdat',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='lastUpdatedat',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='updatedat',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='lga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_lga_item', to='setup.lga'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zone_order_item', to='setup.zone'),
        ),
    ]
