# Generated by Django 6.0.3 on 2026-03-20 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_customer_name_orderitem_sender_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='warehousescan',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='warehousescan',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousescan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='barcode',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flag',
            field=models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('SCANNED_IN', 'Scanned In'), ('WAREHOUSE', 'Warehouse'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('INWARD_RETURNED', 'Inward Returned'), ('OUTWARD_RETURNED', 'Outward Returned')], default='WAREHOUSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_scanned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehousescan',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
