# Generated by Django 6.0.3 on 2026-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_order_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousescan',
            name='flag',
            field=models.CharField(default='IN_WAREHOUSE', max_length=100),
        ),
    ]
