# Generated by Django 6.0.3 on 2026-03-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_logisticspartner_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='logistics_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='logistics.logisticspartner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Partner', 'Logistics Partner')], default='Company', max_length=20),
        ),
    ]
