# Generated by Django 6.0.3 on 2026-03-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_vehicle_logistics_partner_vehicle_owner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='barcode',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='logistics.orderitem'),
        ),
    ]
