# Generated by Django 6.0.3 on 2026-03-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_remove_dispatch_barcode_dispatch_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='logistics.orderitem'),
        ),
    ]
