# Generated by Django 6.0.3 on 2026-03-31 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_dispatch_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='issue_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL', 'Partial'), ('RETURNED', 'Returned'), ('ISSUE', 'Issue')], default='ASSIGNED', max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logistics.dispatch')),
                ('new_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.vehicle')),
                ('old_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.vehicle')),
            ],
        ),
    ]
