# Generated by Django 6.0.3 on 2026-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_dispatch_assigned_by_dispatch_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
