# Generated by Django 6.0.3 on 2026-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_orderitem_delivery_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlocation',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryalert',
            name='alert_type',
            field=models.CharField(choices=[('DEVIATION', 'Route Deviation'), ('DELAY', 'Delivery Delay'), ('STOPPED', 'Agent Stopped'), ('ISSUE', 'Delivery Issue')], default='STOPPED', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryalert',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
    ]
