# Generated by Django 6.0.3 on 2026-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_agentlocation_accuracy_agentlocation_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
