# Generated by Django 6.0.3 on 2026-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_orderitem_latitude_orderitem_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='flag',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('SCANNED_IN', 'Scanned In'), ('WAREHOUSE', 'Warehouse'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('INWARD_RETURNED', 'Inward Returned'), ('OUTWARD_RETURNED', 'Outward Returned')], default='PENDING', max_length=30),
        ),
    ]
