# Generated by Django 6.0.3 on 2026-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_orderitem_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='receiver_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sender_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
