# Generated by Django 6.0.3 on 2026-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_orderitem_receiver_email_orderitem_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='batch_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
