# Generated by Django 6.0.3 on 2026-04-15 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_driverpickup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpickup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverpickup',
            name='created_by',
            field=models.ForeignKey(default=89792688131, on_delete=django.db.models.deletion.CASCADE, related_name='created_batch', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
