# Generated by Django 6.0.3 on 2026-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_driverpickup_created_at_driverpickup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpickup',
            name='flag',
            field=models.CharField(blank=True, default='Pending', max_length=30, null=True),
        ),
    ]
