# Generated by Django 6.0.3 on 2026-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_driverpickup_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='holding_period',
            field=models.IntegerField(default=24),
        ),
    ]
