# Generated by Django 6.0.3 on 2026-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_alter_orderitem_holding_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='holding_period',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
