# Generated by Django 6.0.3 on 2026-04-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_alter_orderitem_holding_period'),
        ('setup', '0014_user_assignedvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, null=True)),
                ('hubName', models.CharField(max_length=100)),
                ('hubAdd', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('hubStatus', models.CharField(default='Active', max_length=200)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hub_created_by', to=settings.AUTH_USER_MODEL)),
                ('hubState', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hub_state', to='setup.nigstate')),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
    ]
