# Generated by Django 6.0.3 on 2026-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_alter_hub_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='createdAt',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
