# Generated by Django 6.0.3 on 2026-04-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_alter_hub_createdat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(default='Pending', max_length=250)),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_batch_no', to='logistics.driverpickup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_created_by', to=settings.AUTH_USER_MODEL)),
                ('desthub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_dest', to='logistics.hub')),
                ('srchub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_src', to='logistics.hub')),
            ],
            options={
                'db_table': 'hubtransfers',
            },
        ),
        migrations.CreateModel(
            name='HubScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('scan_type', models.CharField(blank=True, max_length=250, null=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.hubtransfer')),
            ],
            options={
                'db_table': 'hubscan',
            },
        ),
        migrations.CreateModel(
            name='HubTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.orderitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='logistics.hubtransfer')),
            ],
            options={
                'db_table': 'hubtransferitems',
            },
        ),
    ]
