# Generated by Django 6.0.3 on 2026-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_hubtransfer_hubscan_hubtransferitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubtransferitem',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='hubtransferitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='hubtransferitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
