# Generated by Django 6.0.3 on 2026-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_remove_hubtransferitem_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubtransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
