# Generated by Django 6.0.3 on 2026-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_alter_hubtransfer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpickup',
            name='action_done',
            field=models.CharField(blank=True, default='Dispatched', max_length=30, null=True),
        ),
    ]
