# Generated by Django 6.0.3 on 2026-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_driverpickup_action_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubtransfer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
