# Generated by Django 6.0.3 on 2026-04-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0032_hubtransfer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubscan',
            name='transfer',
        ),
        migrations.AddField(
            model_name='driverpickup',
            name='dispatch_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_hub', to='logistics.hub'),
        ),
        migrations.AddField(
            model_name='hubscan',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hubscan',
            name='transfer_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.hubtransferitem'),
            preserve_default=False,
        ),
    ]
