# Generated by Django 6.0.3 on 2026-04-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0033_remove_hubscan_transfer_driverpickup_dispatch_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubtransferitem',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
