# Generated by Django 6.0.3 on 2026-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_hubtransferitem_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubscan',
            name='barcode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
