# Generated by Django 6.0.3 on 2026-04-26 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0035_hubscan_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubscan',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='hubscan',
            name='scan_type',
        ),
        migrations.AddField(
            model_name='hubscan',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Dispatcher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubscan_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hubscan',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle'),
        ),
        migrations.AlterField(
            model_name='hubscan',
            name='scanned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hubscan_scanned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
