# Generated by Django 6.0.3 on 2026-05-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_remove_hubscan_barcode_remove_hubscan_scan_type_and_more'),
        ('setup', '0025_pricing_unique_subarea_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='lga',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_lga_items', to='setup.lga'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='zone',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zone_order_items', to='setup.zone'),
        ),
    ]
