# Generated by Django 6.0.3 on 2026-05-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0039_orderitem_logistics_o_flag_3998cd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='logistics_o_flag_3998cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='logistics_o_scanned_062a28_idx',
        ),
    ]
