# Generated by Django 6.0.3 on 2026-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0040_remove_orderitem_logistics_o_flag_3998cd_idx_and_more"),
        ("setup", "0027_user_item"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["flag"], name="logistics_o_flag_3998cd_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["scanned_at"], name="logistics_o_scanned_062a28_idx"
            ),
        ),
    ]
