# Generated by Django 6.0.3 on 2026-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0042_remove_vehicle_papersexpirydate_driverdocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("formatted_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hit_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="agentlocation",
            name="barcode",
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("PARTIAL", "Partial"),
                    ("RETURNED", "Returned"),
                    ("ISSUE", "Issue"),
                    ("IN_HUB_TRANSFER", "IN_HUB_TRANSFER"),
                ],
                default="ASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="flag",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_TRANSIT", "In Transit"),
                    ("SCANNED_IN", "Scanned In"),
                    ("WAREHOUSE", "Warehouse"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("INWARD_RETURNED", "Inward Returned"),
                    ("OUTWARD_RETURNED", "Outward Returned"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
