# Generated by Django 6.0.3 on 2026-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0044_alter_addresscache_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresscache",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
