# Generated by Django 6.0.3 on 2026-07-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0047_alter_agentlocation_timestamp_agentcurrentlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlocation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='logistics.dispatchsession'),
        ),
        migrations.AlterField(
            model_name='agentlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
