# Generated by Django 6.0.3 on 2026-07-04 08:25

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0048_alter_agentlocation_session_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="agentlocation",
        #     name="agentname",
        #     field=models.CharField(default="agent", max_length=100),
        # ),
        migrations.CreateModel(
            name="AgentLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.dispatchsession",
                    ),
                ),
                ("agentname", models.CharField(default="agent", max_length=100)),
            ],
        ),
    ]
