# Generated by Django 6.0.3 on 2026-07-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0050_alter_agentlocation_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentlocation',
            name='agentname',
        ),
    ]
