# Generated by Django 6.0.3 on 2026-07-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0051_remove_agentlocation_agentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcurrentlocation',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='logistics.dispatchsession'),
        ),
    ]
