# Generated by Django 6.0.3 on 2026-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0052_agentcurrentlocation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchsession',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
