# Generated by Django 6.0.3 on 2026-07-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0053_dispatchsession_start_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.dispatchsession')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('session', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='DispatchRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='logistics.dispatchstop')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('stop', 'sequence')},
            },
        ),
    ]
