# Generated by Django 6.0.3 on 2026-07-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0054_dispatchstop_dispatchroutepoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('planned_latitude', models.FloatField(blank=True, null=True)),
                ('planned_longitude', models.FloatField(blank=True, null=True)),
                ('deviation_distance', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_deviations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='logistics.dispatchsession')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
