# Generated by Django 6.0.3 on 2026-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0055_routedeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedeviation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
