# Generated by Django 6.0.3 on 2026-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0056_routedeviation_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchstop',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatchstop',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
