# Generated by Django 6.0.3 on 2026-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0057_dispatchstop_completed_dispatchstop_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchstop',
            name='dispatches',
            field=models.ManyToManyField(blank=True, related_name='stops', to='logistics.dispatch'),
        ),
    ]
