# Generated by Django 6.0.3 on 2026-07-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0058_dispatchstop_dispatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='logistics.dispatchsession'),
        ),
    ]
