# Generated by Django 6.0.3 on 2026-04-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('txnRef', models.CharField(default='', max_length=50)),
                ('narration', models.CharField(default='', max_length=200)),
                ('postedBy', models.CharField(default='', max_length=200)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_funding',
            },
        ),
    ]
