# Generated by Django 6.0.3 on 2026-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfunding',
            name='txntype',
            field=models.CharField(default='Credit', max_length=20),
        ),
    ]
