# Generated by Django 6.0.3 on 2026-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_walletfunding_txntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletfunding',
            name='txntype',
            field=models.CharField(default='Income', max_length=20),
        ),
    ]
