# Generated by Django 6.0.3 on 2026-04-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_walletfunding_txntype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IouRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('reason', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('requestDate', models.DateField(auto_now_add=True)),
                ('approvedBy', models.CharField(default='', max_length=200)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iou_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iou_request',
            },
        ),
    ]
