# Generated by Django 6.0.3 on 2026-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_iourequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='iourequest',
            name='iouref',
            field=models.CharField(default='', max_length=50),
        ),
    ]
