# Generated by Django 6.0.3 on 2026-05-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
    ]
