# Generated by Django 6.0.3 on 2026-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expense_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expenseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
