# Generated by Django 6.0.3 on 2026-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_expensedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfunding',
            name='fundtype',
            field=models.CharField(default='Transfer', max_length=20),
        ),
    ]
