# Generated by Django 6.0.3 on 2026-03-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('account', models.BooleanField(default=False)),
                ('operations', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=False)),
                ('settings', models.BooleanField(default=False)),
                ('createdBy', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.CharField(max_length=100, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setup_access',
            },
        ),
    ]
