# Generated by Django 6.0.3 on 2026-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cPayType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='haddress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
