# Generated by Django 6.0.3 on 2026-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_user_cpaytype_user_haddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
