# Generated by Django 6.0.3 on 2026-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_access_createdat_alter_access_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
