# Generated by Django 6.0.3 on 2026-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_user_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
