# Generated by Django 6.0.3 on 2026-03-17 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_user_createdat_user_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='state_creation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_state_creation', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setup_state_lga', to='setup.nigstate')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_zone_createdby', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_zone_lga', to='setup.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_zone_state', to='setup.nigstate')),
            ],
        ),
    ]
