# Generated by Django 6.0.3 on 2026-03-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_nigstate_lga_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nigstate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
