# Generated by Django 6.0.3 on 2026-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_lga_is_active_nigstate_is_active_zone_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='createdBy',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nigstate',
            name='createdBy',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='createdBy',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
