# Generated by Django 6.0.3 on 2026-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_lga_createdby_alter_nigstate_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
