# Generated by Django 6.0.3 on 2026-03-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_logisticspartner_alter_orderitem_lga_and_more'),
        ('setup', '0011_user_api_base_url_user_api_key_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatcher_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchers', to='logistics.logisticspartner'),
        ),
    ]
