# Generated by Django 6.0.3 on 2026-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_user_dispatcher_type_user_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatcher_flag',
            field=models.CharField(blank=True, default='Available', max_length=255, null=True),
        ),
    ]
