# Generated by Django 6.0.3 on 2026-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_user_dispatcher_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignedVehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
