# Generated by Django 6.0.3 on 2026-04-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_driverpickup_action_done'),
        ('setup', '0014_user_assignedvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hub_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_hub', to='logistics.hub'),
        ),
    ]
