# Generated by Django 6.0.3 on 2026-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_remove_auditlog_activity_remove_auditlog_ip_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model'], name='setup_audit_model_df1ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='setup_audit_action_42666e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='setup_audit_created_a18740_idx'),
        ),
    ]
