# Generated by Django 6.0.3 on 2026-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RETRIEVE', 'Retrieve'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login_Failed'), ('LOGOUT', 'Logout')], default='RETRIEVE', max_length=20),
        ),
    ]
