# Generated by Django 6.0.3 on 2026-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0022_bank_expensecategory_user_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
