# Generated by Django 6.0.3 on 2026-05-08 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_bank_is_active_expensecategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subarea', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extrakg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pricetype', models.CharField(default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_creator', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
