# Generated by Django 6.0.3 on 2026-05-14 09:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_pricing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('subarea'), name='unique_subarea_case_insensitive'),
        ),
    ]
