# Generated by Django 6.0.3 on 2026-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_pricing_unique_subarea_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='basekg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricing',
            name='extraprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_rship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
