# Generated by Django 6.0.3 on 2026-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_pricing_basekg_pricing_extraprice_user_guarantor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='item',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
