# Generated by Django 6.0.3 on 2026-06-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0027_user_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='dispatcher',
            field=models.BooleanField(default=False),
        ),
    ]
