# Generated by Django 6.0.3 on 2026-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_access_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Marketer', 'Marketer'), ('Account', 'Account'), ('Dispatcher', 'Dispatcher'), ('Superadmin', 'Superadmin'), ('Customer', 'Customer')], default='Customer', max_length=25),
        ),
    ]
