# Generated by Django 6.0.3 on 2026-08-24 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0030_notificationconfig_notificationtype_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='setup.notificationtype'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('notification_type', 'channel'), name='unique_notification_type_channel'),
        ),
    ]
