# Generated by Django 6.0.3 on 2026-08-24 21:24

from django.db import migrations


def create_notification_types(apps, schema_editor):

    NotificationType = apps.get_model("setup", "NotificationType")

    notification_types = [
        {
            "code": "ORDER_CREATED",
            "name": "Order Created",
            "description": "Sent when a new order is created.",
        },
        {
            "code": "ORDER_PICKED_UP",
            "name": "Order Picked Up",
            "description": "Sent when an order has been picked up.",
        },
        {
            "code": "ORDER_IN_TRANSIT",
            "name": "Order In Transit",
            "description": "Sent when an order is in transit.",
        },
        {
            "code": "OUT_FOR_DELIVERY",
            "name": "Out For Delivery",
            "description": "Sent when an order is out for delivery.",
        },
        {
            "code": "ORDER_DELIVERED",
            "name": "Order Delivered",
            "description": "Sent when an order has been delivered.",
        },
        {
            "code": "ORDER_PART_DELIVERED",
            "name": "Partially Delivered",
            "description": "Sent when only part of an order has been delivered.",
        },
        {
            "code": "ORDER_RETURNED",
            "name": "Order Returned",
            "description": "Sent when an order has been returned.",
        },
        {
            "code": "ORDER_DAMAGED",
            "name": "Order Damaged",
            "description": "Sent when an order is marked as damaged.",
        },
        {
            "code": "ORDER_LOST",
            "name": "Order Lost",
            "description": "Sent when an order is marked as lost.",
        },
        {
            "code": "CAMPAIGN",
            "name": "Campaign",
            "description": "Used for customer campaigns.",
        },
        {
            "code": "GENERAL_NOTIFICATION",
            "name": "General Notification",
            "description": "Used for general customer notifications.",
        },
    ]

    for item in notification_types:

        NotificationType.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "description": item["description"],
                "is_active": True,
            },
        )


def remove_notification_types(apps, schema_editor):

    NotificationType = apps.get_model("setup", "NotificationType")

    NotificationType.objects.filter(
        code__in=[
            "ORDER_CREATED",
            "ORDER_PICKED_UP",
            "ORDER_IN_TRANSIT",
            "OUT_FOR_DELIVERY",
            "ORDER_DELIVERED",
            "ORDER_PART_DELIVERED",
            "ORDER_RETURNED",
            "ORDER_DAMAGED",
            "ORDER_LOST",
            "CAMPAIGN",
            "GENERAL_NOTIFICATION",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "setup",
            "0031_alter_notificationtype_options_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_notification_types,
            remove_notification_types,
        ),
    ]
