# Generated by Django 6.0.3 on 2026-08-31 11:18

from django.db import migrations


def seed_notification_templates(apps, schema_editor):
    NotificationType = apps.get_model("setup", "NotificationType")
    NotificationTemplate = apps.get_model("setup", "NotificationTemplate")

    templates = {
        "ORDER_CREATED": {
            "email_subject": "Your Paveway Order Has Been Created",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been successfully created with Paveway Logistics.</p>

<div>
    <strong>Order Details</strong>
</div>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}
</p>

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} has been created successfully. "
                "Waybill: {{ waybill_no|default:barcode }}."
            ),
        },
        "ORDER_PICKED_UP": {
            "email_subject": "Your Paveway Order Has Been Picked Up",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    Your order has been picked up and is now in the possession
    of Paveway Logistics.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}
</p>

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} has been picked up. "
                "Waybill: {{ waybill_no|default:barcode }}."
            ),
        },
        "ORDER_IN_TRANSIT": {
            "email_subject": "Your Paveway Order Is In Transit",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    Your order is currently in transit and is on its way to the
    delivery destination.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}
</p>

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} is now in transit. "
                "Waybill: {{ waybill_no|default:barcode }}."
            ),
        },
        "ORDER_OUT_FOR_DELIVERY": {
            "email_subject": "Your Paveway Order Is Out for Delivery",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    Your order is now out for delivery and will be delivered to you soon.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Driver:</strong> {{ agent_name }}<br>
    <strong>Driver Phone:</strong> {{ agent_phone }}
</p>

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} is out for delivery. "
                "Waybill: {{ waybill_no|default:barcode }}. "
                "Driver: {{ agent_name }}."
            ),
        },
        "ORDER_DELIVERED": {
            "email_subject": "Your Paveway Order Has Been Delivered",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    Your order has been delivered successfully.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}<br>
    <strong>Driver:</strong> {{ agent_name }}<br>
    <strong>Driver Phone:</strong> {{ agent_phone }}
</p>

{% if comment %}
<p>
    <strong>Delivery Comment:</strong><br>
    {{ comment }}
</p>
{% endif %}

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} has been delivered successfully. "
                "Waybill: {{ waybill_no|default:barcode }}."
            ),
        },
        "ORDER_PARTIAL": {
            "email_subject": "Update on Your Paveway Order",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    There has been an update to your Paveway order.
    The order has been partially delivered.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}
</p>

{% if comment %}
<p>
    <strong>Delivery Comment:</strong><br>
    {{ comment }}
</p>
{% endif %}

<p>Thank you for using Paveway Logistics.</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} has been partially delivered. "
                "Waybill: {{ waybill_no|default:barcode }}. "
                "Comment: {{ comment }}."
            ),
        },
        "ORDER_RETURNED": {
            "email_subject": "Your Paveway Order Has Been Returned",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    Your order has been returned and could not be completed as planned.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}
</p>

{% if comment %}
<p>
    <strong>Reason:</strong><br>
    {{ comment }}
</p>
{% endif %}

<p>
    Please contact Paveway Logistics if you require further information.
</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "Your Paveway order {{ order_no }} has been returned. "
                "Waybill: {{ waybill_no|default:barcode }}. "
                "Reason: {{ comment }}."
            ),
        },
        "ORDER_ISSUE": {
            "email_subject": "Issue With Your Paveway Order",
            "email_body": """
<p>Dear {{ receiver }},</p>

<p>
    There is an issue with the delivery of your Paveway order.
</p>

<p>
    <strong>Order No:</strong> {{ order_no }}<br>
    <strong>Vendor Order No:</strong> {{ vendor_order_no }}<br>
    <strong>Waybill No:</strong> {{ waybill_no|default:barcode }}<br>
    <strong>Barcode:</strong> {{ barcode }}<br>
    <strong>Status:</strong> {{ status }}
</p>

{% if comment %}
<p>
    <strong>Issue Details:</strong><br>
    {{ comment }}
</p>
{% endif %}

<p>
    Please contact Paveway Logistics if you require further information.
</p>

<p>
    © {{ year }} Paveway Logistics.<br>
    This is an automated notification. Please do not reply.
</p>
""",
            "sms_body": (
                "There is an issue with your Paveway order {{ order_no }}. "
                "Waybill: {{ waybill_no|default:barcode }}. "
                "Details: {{ comment }}."
            ),
        },
    }

    for code, data in templates.items():

        notification_type = NotificationType.objects.filter(code=code).first()

        if not notification_type:
            continue

        NotificationTemplate.objects.update_or_create(
            notification_type=notification_type,
            channel="EMAIL",
            defaults={
                "subject": data["email_subject"],
                "body": data["email_body"].strip(),
                "is_active": True,
            },
        )

        NotificationTemplate.objects.update_or_create(
            notification_type=notification_type,
            channel="SMS",
            defaults={
                "subject": "",
                "body": data["sms_body"],
                "is_active": True,
            },
        )


def reverse_seed_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("setup", "NotificationTemplate")

    NotificationTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("setup", "0033_alter_notificationlog_options_and_more"),
    ]
    operations = [
        migrations.RunPython(
            seed_notification_templates,
            reverse_seed_notification_templates,
        ),
    ]
