# Generated by Django 6.0.3 on 2026-08-31 11:59

from django.db import migrations


def seed_notification_templates(apps, schema_editor):
    NotificationType = apps.get_model("setup", "NotificationType")
    NotificationTemplate = apps.get_model("setup", "NotificationTemplate")

    templates = {
        "ORDER_CREATED": {
            "EMAIL": {
                "subject": "Your Paveway Order Has Been Created",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been successfully created with Paveway Logistics.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Vendor Order No:</strong> {{ vendor_order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been created successfully. Order No: {{ order_no }}. Waybill: {{ waybill_no }}.",
            },
        },
        "ORDER_PICKED_UP": {
            "EMAIL": {
                "subject": "Your Paveway Order Has Been Picked Up",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been picked up and is now being processed for delivery.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Vendor Order No:</strong> {{ vendor_order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been picked up and is being processed for delivery. Waybill: {{ waybill_no }}.",
            },
        },
        "ORDER_IN_TRANSIT": {
            "EMAIL": {
                "subject": "Your Paveway Order Is In Transit",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order is currently in transit.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

<p>We will keep you updated as your order progresses.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order is now in transit. Waybill: {{ waybill_no }}.",
            },
        },
        "OUT_FOR_DELIVERY": {
            "EMAIL": {
                "subject": "Your Paveway Order Is Out For Delivery",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order is now out for delivery.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

<p>Please ensure that someone is available to receive the package.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order is out for delivery. Please ensure someone is available to receive it. Waybill: {{ waybill_no }}.",
            },
        },
        "ORDER_DELIVERED": {
            "EMAIL": {
                "subject": "Your Paveway Order Has Been Delivered",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your Paveway order has been delivered successfully.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been delivered successfully. Waybill: {{ waybill_no }}.",
            },
        },
        "ORDER_PART_DELIVERED": {
            "EMAIL": {
                "subject": "Update on Your Paveway Order",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been partially delivered.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

{% if comment %}
<p><strong>Comment:</strong> {{ comment }}</p>
{% endif %}

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been partially delivered. Waybill: {{ waybill_no }}. {% if comment %}Comment: {{ comment }}.{% endif %}",
            },
        },
        "ORDER_RETURNED": {
            "EMAIL": {
                "subject": "Your Paveway Order Has Been Returned",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been returned.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

{% if comment %}
<p><strong>Reason:</strong> {{ comment }}</p>
{% endif %}

<p>Please contact us if you require further information.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been returned. Waybill: {{ waybill_no }}. {% if comment %}Reason: {{ comment }}.{% endif %}",
            },
        },
        "ORDER_DAMAGED": {
            "EMAIL": {
                "subject": "Issue With Your Paveway Order",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been reported as damaged.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

{% if comment %}
<p><strong>Details:</strong> {{ comment }}</p>
{% endif %}

<p>Our team will review the matter and provide further assistance.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been reported as damaged. Waybill: {{ waybill_no }}. {% if comment %}Details: {{ comment }}.{% endif %}",
            },
        },
        "ORDER_LOST": {
            "EMAIL": {
                "subject": "Issue With Your Paveway Order",
                "body": """
<p>Dear {{ receiver }},</p>

<p>Your order has been reported as lost.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

{% if comment %}
<p><strong>Details:</strong> {{ comment }}</p>
{% endif %}

<p>Our team will review the matter and provide further assistance.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "Your Paveway order has been reported as lost. Waybill: {{ waybill_no }}. {% if comment %}Details: {{ comment }}.{% endif %}",
            },
        },
        "ORDER_ISSUE": {
            "EMAIL": {
                "subject": "Issue With Your Paveway Order",
                "body": """
<p>Dear {{ receiver }},</p>

<p>There is an issue with your Paveway order.</p>

<p><strong>Order No:</strong> {{ order_no }}</p>
<p><strong>Waybill No:</strong> {{ waybill_no }}</p>

{% if comment %}
<p><strong>Details:</strong> {{ comment }}</p>
{% endif %}

<p>Our team will review the issue and provide further assistance.</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "There is an issue with your Paveway order. Waybill: {{ waybill_no }}. {% if comment %}Details: {{ comment }}.{% endif %}",
            },
        },
        "CAMPAIGN": {
            "EMAIL": {
                "subject": "Paveway Logistics",
                "body": """
<p>Dear {{ receiver }},</p>

<p>{{ message }}</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "{{ message }}",
            },
        },
        "GENERAL_NOTIFICATION": {
            "EMAIL": {
                "subject": "Paveway Logistics Notification",
                "body": """
<p>Dear {{ receiver }},</p>

<p>{{ message }}</p>

<p>Thank you for using Paveway Logistics.</p>
""",
            },
            "SMS": {
                "subject": "",
                "body": "{{ message }}",
            },
        },
    }

    for notification_code, channels in templates.items():

        try:
            notification_type = NotificationType.objects.get(code=notification_code)
        except NotificationType.DoesNotExist:
            continue

        for channel, template_data in channels.items():

            NotificationTemplate.objects.update_or_create(
                notification_type=notification_type,
                channel=channel,
                defaults={
                    "subject": template_data["subject"],
                    "body": template_data["body"].strip(),
                    "is_active": True,
                },
            )


def remove_notification_templates(apps, schema_editor):
    NotificationType = apps.get_model("setup", "NotificationType")
    NotificationTemplate = apps.get_model("setup", "NotificationTemplate")

    codes = [
        "ORDER_CREATED",
        "ORDER_PICKED_UP",
        "ORDER_IN_TRANSIT",
        "OUT_FOR_DELIVERY",
        "ORDER_DELIVERED",
        "ORDER_PART_DELIVERED",
        "ORDER_RETURNED",
        "ORDER_DAMAGED",
        "ORDER_LOST",
        "ORDER_ISSUE",
        "CAMPAIGN",
        "GENERAL_NOTIFICATION",
    ]

    NotificationTemplate.objects.filter(notification_type__code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("setup", "0034_seed_notification_templates"),
    ]

    operations = [
        migrations.RunPython(
            seed_notification_templates,
            remove_notification_templates,
        ),
    ]
