# Generated by Django 6.0.3 on 2026-09-01 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0035_seed_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
