# Generated by Django 6.0.3 on 2026-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_ticket_created_at_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flag',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
