# Generated by Django 6.0.3 on 2026-06-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_ticket_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdetail',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.ticket'),
        ),
    ]
